# This file configures your Netlify deployment.

[build]
  # This command tells Netlify where your public website files are.
  publish = "/"
  # This tells Netlify where your serverless functions are.
  functions = "netlify/functions/"

# This rule makes sure that all requests go to your index.html,
# which is standard for single-page applications and PWAs.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
